name: smc-binding-analysis
channels:
  - sjcross
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asteval=1.0.6
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cachetools=5.5.1
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - fonttools=4.55.3
  - freetype=2.12.1
  - future=1.0.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.14.0
  - h5py=3.12.1
  - hdf5=1.14.5
  - httpcore=1.0.2
  - httpx=0.27.0
  - idna=3.7
  - imageio=2.37.0
  - iniconfig=1.1.1
  - ipykernel=6.29.5
  - ipympl=0.9.3
  - ipython=8.30.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - kymotools=0.4.5
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-aarch64=2.40
  - lerc=4.0.0
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - lmfit=1.3.3
  - lumicks.pylake=1.6.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.16
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.1.4
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.8.0
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - scikit-image=0.25.0
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - send2trash=1.8.2
  - setuptools=75.8.0
  - setuptools-scm=8.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.13.3
  - tabulate=0.8.10
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tifffile=2025.2.18
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - uncertainties=3.2.2
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
